services:

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cultivafacil
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: presentation-frontend/src/main/react
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: