package br.edu.cesar.cultivafacil.domain.insumo.plano;

public enum InsumoErroCodigo {
    MES_REFERENCIA_PASSADO,
    PLANO_DUPLICADO,
    TIPO_INSUMO_INVALIDO,
    QUANTIDADE_INSUMO_INVALIDA,
    PRECO_UNITARIO_OBRIGATORIO,
    REVERSAO_STATUS_INVALIDA,
    INSUMO_SEM_AQUISICAO,
    SALDO_INSUFICIENTE,
    UNIDADE_INCOMPATIVEL,
    LIMITE_INVALIDO,
    EMAIL_DESTINATARIO_OBRIGATORIO,
    CONFIGURACAO_LIMITE_DUPLICADA
}